# Generated by Django 2.2.6 on 2019-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('total_value', models.IntegerField()),
                ('disk_usage', models.FloatField()),
                ('latency', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
